package commands

import JENV_HOME
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.arguments.validate
import okio.FileSystem
import okio.Path.Companion.toPath
import utils.AliasesGenerator
import utils.CommandExecuter
import utils.FileSystemUtils
import utils.isWindows
import kotlin.experimental.ExperimentalNativeApi

@OptIn(ExperimentalNativeApi::class)
class Add: CliktCommand(help="Add JDK into jenv. A alias name will be generated by parsing \"java -version\"") {
    private val javaBinarySubpath = "bin/java${if (Platform.isWindows()) ".exe" else ""}"
    private val jdkPath: String by argument().validate {
        val javaBinPath = it.toPath().resolve(javaBinarySubpath)
        require(FileSystem.SYSTEM.exists(javaBinPath)) {
            "$jdkPath is not a valid path to java installation"
        }
    }

    override fun run() {
        val javaVersion = CommandExecuter.executeCommand("$jdkPath/$javaBinarySubpath -version")
        AliasesGenerator.generateAliases(javaVersion)
            .forEach {
                FileSystemUtils.createLink(jdkPath.toPath(), "$JENV_HOME/versions/$it".toPath())
            }
    }
}