package commands

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.arguments.validate
import okio.FileSystem
import okio.Path.Companion.toPath

class Add: CliktCommand(help="Add JDK into jenv. A alias name will be generated by parsing \"java -version\"") {
    private val path: String by argument().validate {
        val javaBinPath = it.toPath().resolve("bin/java")
        require(FileSystem.SYSTEM.exists(javaBinPath)) {
            "$path is not a valid path to java installation"
        }
    }

    override fun run() {
        echo("Add JDK into jenv.")
    }
}